### ISSUE TITLE
support different relayer account on source chain and target chain

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/relayer#14]

**Comment by kcraftcode** [comment]
To make this solution work, the most important technical challenges revolve around cross-chain compatibility and ensuring smooth communication between different blockchains. The key is designing a system that allows different relayers to operate on both the source and target chains without issues.

One of the big concerns is security. You need to make sure that the relayer accounts are properly authenticated and secured. The last thing anyone wants is unauthorized transactions messing things up. Along with that, managing gas fees across chains is critical. Different chains have different transaction costs, so it’s essential to optimize this part to keep the relayers efficient.

Handling events between the two chains is also crucial. You need to ensure that when something happens on the source chain, it gets reliably communicated to the target chain. This means setting up robust message passing and event triggers.

Flexibility is key too—there should be a way to easily configure and switch relayer accounts without any downtime. And, of course, dealing with network delays and ensuring transactions are finalized correctly is something that can't be overlooked. Different chains operate at different speeds, so you'll need to handle that carefully.

Finally, you need a solid plan for failures. If something goes wrong, the system should have a way to detect it and retry without causing issues or losing funds.

These are the core technical areas that need to be addressed, and I’m confident I can build a system that tackles them efficiently.

**Comment by xiaoch05** [comment]
https://github.com/helix-bridge/relayer/pull/45
