### ISSUE TITLE
Support any EVM chain multi-signature wallet

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/relayer#21]

**Comment by xiaoch05** [comment]
https://github.com/xapi-box/xapi/blob/main/src/SubAPIMultiSig.sol

**Comment by xiaoch05** [comment]
https://github.com/xapi-box/xapi/blob/9b8603ea7961a7241cdbb9a05ab3241cee87540a/src/SubAPISignaturePub.sol#L15

**Comment by YoshiyukiSakura** [comment]
Task Requirements

Reference the XAPI multi-signature verification to implement a similar multi-signature wallet for Helix, enabling Helix to use the multi-signature wallet to perform the role of a relayer on any EVM chain.

- [ ] 	1.	Implement On-chain Multi-Signature Verification Contract & Multi-Signature Collection Contract: Reference the existing implementation in XAPI.
- [ ] 	2.	Store Multi-Signature Information On-chain: It is recommended to store multi-signature information directly on the blockchain to avoid centralization issues associated with storing it on an index server.
- [ ] 	3.	Adapt Relayer Client Code: Complete the submission, querying, and execution of signed transactions by integrating with the multi-signature information.
- [ ] 	4.	Automate Multi-Signature Verification Contract Deployment and Integration with New Chains: Automate the process to deploy multi-signature verification contracts and integrate with new chains.
